# Use postgres/example user/password credentials
version: "3.1"

services:
  nodered:
    build: .
    restart: always
    environment:
      - TZ=Australia/Sydney
      - NODE_RED_ENABLE_PROJECTS=true
    ports:
      - 1880:1880
    volumes:
      - ./:/data
